### ISSUE TITLE
Labels en URI's van gegenereerde attributen in gevallen met associatieklassen in sommige gevallen niet gedisambigueerd

### ISSUE THREAD

**Issue by mvanbrab** [bertvannuffelen/demo_oslodoc#13]
[Edit1: aangepast aan de gewijzigde klassenamen (starten met K nu ter verduidelijking)]
[Edit2: grondige aanpassing, zie ook mijn volgende comment]
[Edit3: verdere aanpassing na commentaar Bert: suffix alleen als source en target klasse dezelfde zijn]
[Edit4: nu de suffixen ".source en ".target" zeldzaam zullen zijn, beter niet afkorten. In de gevallen waar ze nu nog nodig zijn (zie specificatie) zijn ze nu een welkome verduidelijking. De suggestie tot afkorten dus verwijderd.]
[Edit5: gereduceerd tot wat nu nog verkeerd gaat (ook omdat de testcase hernummerd zijn)]

**Volgende principes zouden moeten gelden:**
- Waar binnen één klasse twee keer een zelfde label-nl zou worden gegenereerd als gevolg van eenzelfde associatie, zou een suffix ter disambiguatie moeten worden toegevoegd aan het label-nl.
- Weer binnen één package twee keer een zelfde uri zou worden gegenereerd als gevolg van eenzelfde associatie, zou een suffix ter disambiguatie moeten worden toegevoegd aan de uri.

**Waar de suffixen op heden ontbreken:**
- in K22 (ten gevolge van zelf-associatie): label-nl en URI van de twee voorkomende heeft02 attributen
- in K26 (ten gevolge van zelf-associatie in combinatie met associatieklasse): label-nl en URI van de twee voorkomende heeft26 attributen

**Voorstel suffixen:**
.source
.target

**Comment by mvanbrab** [comment]
Ik heb dit issue (titel en inhoud) aangepast nadat ik inzag dat een toevoegsel toch nodig is (voor het geval de associatie een self-associatie zou zijn). Blijft over: kleine letter in label en URI, toevoeging prefix in URI, eventueel alternatief voor voluit geschreven ".source" en ".target".

**Comment by bertvannuffelen** [comment]
de self associatie daar had ik nog niet aangedacht.

**Comment by bertvannuffelen** [comment]
@mvanbrab  voeg je deze case ook toe ?

voorstel van oplossing: als de EAName van Source en Dest hetzelfde is, voeg een suffix toe anders niet.

**Comment by mvanbrab** [comment]
OK, zeer elegant voorstel!
Als je dat ziet zitten in de code...
Ik pas de initiële comment van dit issue aan en... er volgt dus een nieuwe versie van de spec (en de testen...), zie #19.

**Comment by mvanbrab** [comment]
Nieuwe testcase (09) beschikbaar.

**Comment by bertvannuffelen** [comment]
a) eerste feedback: er staat nu een warning op het gebruik van een expliciete URI. Omdat we moeten prefixen met de classname, maar we een object krijgen met een externe URI wordt er een warning gezet en is de waarde null
Als iemand dus een expliciete URI gebruikt dan kan ie dit niet gebruiken.

**Comment by bertvannuffelen** [comment]
b) labels updaten is misschien wel een probleem. Want dat lijkt me echt wel geen zinvolle keuze. Misschien moeten we optie K22 gewoon laten vallen en enkel optie K23 toelaten.

**Comment by mvanbrab** [comment]
Als antwoord op a) en b) van @bertvannuffelen. Verder overleg graag in meeting... 

a) Inderdaad, voor expliciete URI's (met uri tag); dat is de reden voor mijn issue #24. Maar hier gaat het over door de toolchain berekende URI's, die moeten hier dus wel degelijk gedisambigueerd worden, tenzij we associaties in twee richtingen alleen maar zouden ondersteunen met rollen aan beide kanten in plaats van een associatienaam. Dan vervallen de gevallen met associatie Heeft02, Heeft06, Heeft22, Heeft26; iets waar AWV wel op rekent.

b) Labels 'updaten' is hier niet van toepassing. Het gaat hier over labels 'creëren'. Je deed het al in associatieklassen Heeft25, Heeft26 om k25, k26 te disambiguren.

**Comment by bertvannuffelen** [comment]
beslissing: ambiguatie doen met suffixen .source en .target

**Comment by mvanbrab** [comment]
Oplossing in meeting 2019-08-25:
- labels: altijd met .source en .target waar disambiuatie nodig is
- uri's: idem voor zelf te genereren uri's; dit geeft een probleem met vooraf toegekende uri. Dan wordt tweemaal dezelfde uri gebruikt voor een verschillend attribuut. Dit is bijna altijd verkeerd. Warning genereren plus toelichten in de modelleringsregels.

**Comment by bertvannuffelen** [comment]
TODO: juiste warning genereren.

**Comment by mvanbrab** [comment]
Na update toolchain: op dit ogenblik wordt dit geval correct behandeld.

TODO1: De testgevallen in deze specificatie https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/UML2RDF/AssociatiesEnRollen/Specificatie%20attributen%20gegenereerd%20voor%20associaties.pdf allemaal opnieuw evalueren + opgeloste fouten afvinken (groen maken).

TODO2: Ik zie nog een afwijking voor Heeft26_naam in de URI's. Afsplitsen in nieuw issue en dan dit issue sluiten.

**Comment by mvanbrab** [comment]
Is opgelost
