### ISSUE TITLE
Definition en usage note bij gegenereerde attributen in associatieklassen

### ISSUE THREAD

**Issue by mvanbrab** [bertvannuffelen/demo_oslodoc#14]
Een definitie is noodzakelijk. Ik zou de nu gegenereerde "a definition" vervangen door iets automatisch doch unieks en zinvols, bvb. "Linkt klasse K07A in associatieklasse Heeft07".

Een usage note is optioneel. Ik zou de nu gegenereerde "a usage" gewoon weglaten.

**Comment by bertvannuffelen** [comment]
Ik heb een formulering zonder dynamische tekst toegevoegd. Want dat vereist heel wat ontwikkeling.

**Comment by mvanbrab** [comment]
Pragmatisch dan (kan ik perfect mee leven):
- geen usage note
- definition-nl: "Linkt geassocieerde klasse."

**Comment by mvanbrab** [comment]
Oplossing in meeting 2019-08-25:
- "Referentie naar verbonden klasse."
- Later enhancement: dynamisch tekstje dat verbonden klasse aanduidt bij naam.

**Comment by mvanbrab** [comment]
Getest en goed bevonden.
