### ISSUE TITLE
fix lege kolommen Eigenschap en Beschrijving K23

### ISSUE THREAD

**Issue by mvanbrab** [bertvannuffelen/demo_oslodoc#31]
Info uit de rollen op de associatieuiteinden wordt niet gelezen.

**Comment by mvanbrab** [comment]
Testcase (AP): https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/documentatie/associaties#K%2023
en ook de naamloze eigenschappen in het corresponderende vocabularium
https://otl-test.data.vlaanderen.be/doc/vocabularium/documentatie/associaties-voc

**Comment by bertvannuffelen** [comment]
De issue is zichtbaar hier https://github.com/Informatievlaanderen/OSLO-Generated/blob/test-feature-checkout/report/doc/applicatieprofiel/documentatie/associaties/all-associaties.jsonld#L7478

**Comment by mvanbrab** [comment]
Na update toolchain: op dit ogenblik wordt dit geval correct behandeld.

TODO: De testgevallen in deze specificatie https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/UML2RDF/AssociatiesEnRollen/Specificatie%20attributen%20gegenereerd%20voor%20associaties.pdf allemaal opnieuw evalueren + opgeloste fouten afvinken (groen maken).
