### ISSUE TITLE
Gevallen met associatieklasse nog te ondersteunen

### ISSUE THREAD

**Issue by mvanbrab** [bertvannuffelen/demo_oslodoc#5]
Gevallen met associatieklasse, nieuwe situatie (gevallen 06 en 07) zijn nog te ondersteunen in de toolchain

**Comment by bertvannuffelen** [comment]
worden nu ondersteund

- [ ] een definitie benodigd
- [ ] een gebruiksnota benodigd

**Comment by mvanbrab** [comment]
Deze gevallen worden nu blijkbaar ondersteund. Ik ga deze issue dus sluiten en eventuele opmerkingen over associatieklassen in individuele issues onderbrengen.
